"""create profiles skills tables

Revision ID: a4505a422672
Revises: 5b0ffb088835
Create Date: 2026-06-18 18:32:34.175586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4505a422672'
down_revision: Union[str, Sequence[str], None] = '5b0ffb088835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('profile_skills',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'skill_id')
    )
    op.add_column('profiles', sa.Column('name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('role', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('experience_type', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('company', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('portfolio_url', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('resume_url', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('github_url', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('x_url', sa.Text(), nullable=True))
    op.create_index(op.f('ix_profiles_company'), 'profiles', ['company'], unique=False)
    op.create_index(op.f('ix_profiles_experience_type'), 'profiles', ['experience_type'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_role'), 'profiles', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_role'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_experience_type'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_company'), table_name='profiles')
    op.drop_column('profiles', 'x_url')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'github_url')
    op.drop_column('profiles', 'resume_url')
    op.drop_column('profiles', 'portfolio_url')
    op.drop_column('profiles', 'company')
    op.drop_column('profiles', 'experience_type')
    op.drop_column('profiles', 'role')
    op.drop_column('profiles', 'name')
    op.drop_table('profile_skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
